import { useEffect, useMemo, useState } from 'react'
import Card from '../components/Card'
import { firebaseEnabled } from '../firebase/config'
import { ensureAnonymousUser } from '../firebase/auth'
import { createRoom, joinRoom, playMove, setTeam, startNextRound, startRoom, watchPrivateGame, watchRoom } from '../firebase/database'
import { getPlayerId } from '../utils/roomCode'
import { findCombinations, legalCaptures } from '../game/captureRules'
import { isValidBuild } from '../game/buildRules'
import { cardValue, suitSymbol } from '../game/cardUtils'

const remembered = () => localStorage.getItem('casino_room_code') || ''
const invite = () => new URLSearchParams(location.search).get('room')?.trim().toUpperCase() || ''

export default function HomePage() {
  const playerId = useMemo(() => getPlayerId(), []); const savedRoom = useMemo(() => remembered(), []); const inviteRoom = useMemo(() => invite(), [])
  const [mode, setMode] = useState(savedRoom ? 'loading' : inviteRoom ? 'join' : 'home'); const [name, setName] = useState(''); const [roomCode, setRoomCode] = useState(savedRoom || inviteRoom); const [joinedRoom, setJoinedRoom] = useState(savedRoom)
  const [room, setRoom] = useState(null); const [privateGame, setPrivateGame] = useState(null); const [user, setUser] = useState(null); const [message, setMessage] = useState(firebaseEnabled ? 'Connecting…' : 'Firebase is not configured.')
  useEffect(() => { if (firebaseEnabled) ensureAnonymousUser().then((next) => { setUser(next); setMessage('') }).catch(() => setMessage('Could not connect to Firebase.')) }, [])
  useEffect(() => { if (!user || !joinedRoom) return; return watchRoom(joinedRoom, (next) => { setRoom(next); setMode(next ? (next.status === 'lobby' ? 'lobby' : 'game') : 'home'); if (!next) setMessage('Room not found.') }) }, [user, joinedRoom])
  useEffect(() => { if (!user || !joinedRoom || room?.status !== 'playing') return; return watchPrivateGame(joinedRoom, playerId, setPrivateGame) }, [user, joinedRoom, playerId, room?.status])
  const enter = async (task) => { if (!user) return setMessage('Still connecting.'); if (!name.trim()) return setMessage('Enter your name first.'); try { const code = await task(); localStorage.setItem('casino_room_code', code); setRoomCode(code); setJoinedRoom(code); setMessage('') } catch (error) { setMessage(error.message) } }
  const leave = () => { localStorage.removeItem('casino_room_code'); setJoinedRoom(''); setRoomCode(''); setRoom(null); setPrivateGame(null); setMode('home') }
  if (mode === 'lobby' && room) return <Lobby room={room} playerId={playerId} setMessage={setMessage} leave={leave} />
  if (mode === 'game' && room) return <Game room={room} privateGame={privateGame} playerId={playerId} setMessage={setMessage} leave={leave} />
  return <Shell><div className="mx-auto max-w-md pt-20 text-center"><p className="text-xs tracking-[.4em] text-amber-300">CLASSIC CARD GAME</p><h1 className="mt-2 text-6xl font-black">CASSINO</h1>{mode === 'home' ? <div className="mt-10 grid gap-3"><Button onClick={() => setMode('create')}>Create game</Button><Button secondary onClick={() => setMode('join')}>Join game</Button></div> : <div className="mt-10 rounded-3xl bg-[#173128] p-5 text-left"><h2 className="text-xl font-black">{mode === 'join' ? 'Join a game' : 'Create a game'}</h2>{mode === 'join' && <Field label="Room code" value={roomCode} setValue={(value) => setRoomCode(value.toUpperCase())} placeholder="AB7K9C" /> }<Field label="Your name" value={name} setValue={setName} placeholder="Saroj" /><Button onClick={() => mode === 'join' ? enter(() => joinRoom({ roomCode, playerId, authUid: user.uid, name })) : enter(() => createRoom({ playerId, authUid: user.uid, name }))}>{mode === 'join' ? 'Join room' : 'Create room'}</Button><button className="mt-4 w-full text-sm underline" onClick={() => setMode('home')}>Back</button></div>}<Message text={message} /></div></Shell>
}

function Lobby({ room, playerId, setMessage, leave }) { const players = Object.values(room.players || {}).sort((a, b) => a.slot - b.slot); const host = room.hostPlayerId === playerId; const counts = players.reduce((all, player) => ({ ...all, [player.team]: (all[player.team] || 0) + 1 }), {}); const ready = players.length === 4 && counts[1] === 2 && counts[2] === 2
  return <Shell><div className="mx-auto max-w-xl py-8"><h1 className="text-center text-4xl font-black">CASSINO</h1><section className="mt-5 rounded-3xl bg-[#173128] p-5 text-center"><p className="text-xs tracking-widest">ROOM CODE</p><p className="text-4xl font-black tracking-[.2em] text-amber-300">{room.roomCode}</p><button className="mt-3 text-sm underline" onClick={() => navigator.clipboard.writeText(room.roomCode)}>Copy code</button></section><section className="mt-4 rounded-3xl bg-[#173128] p-5"><div className="mb-3 flex justify-between"><b>Players</b><span>{players.length}/4</span></div>{[1,2,3,4].map((slot) => { const player = players.find((item) => item.slot === slot); return <div key={slot} className="mb-2 flex items-center justify-between rounded-xl bg-black/20 p-3">{player ? <><span><b>{player.name}</b> <small>Player {slot} {player.isHost && 'HOST'}</small></span>{host ? <select disabled={room.teamsLocked} value={player.team} onChange={(event) => setTeam({ roomCode: room.roomCode, playerId, hostPlayerId: room.hostPlayerId, targetPlayerId: player.playerId, team: Number(event.target.value) }).catch((error) => setMessage(error.message))} className="rounded bg-[#244638] p-1"><option value={1}>Team 1</option><option value={2}>Team 2</option></select> : <span>Team {player.team}</span>}</> : <span>Waiting for Player {slot}</span>}</div> })}</section>{host ? <div className="mt-4"><Button disabled={!ready} onClick={() => startRoom({ roomCode: room.roomCode, playerId }).catch((error) => setMessage(error.message))}>{ready ? 'Start game' : 'Need 4 players · 2 per team'}</Button></div> : <p className="mt-5 text-center">Waiting for host to start…</p>}<button className="mt-6 w-full text-sm underline" onClick={leave}>Leave</button></div></Shell> }

function Game({ room, privateGame, playerId, setMessage, leave }) { const [selected, setSelected] = useState(null); const [mode, setMode] = useState('choose'); const [targets, setTargets] = useState([]); const game = room.game; const me = game?.players?.[playerId]; if (!game || !me || !privateGame) return <Shell><p className="pt-28 text-center">Dealing cards...</p></Shell>; if (game.phase === 'game-over' || game.phase === 'round-result') return <Result room={room} game={game} playerId={playerId} setMessage={setMessage} leave={leave} />; const myTurn = game.currentSlot === me.slot; const card = privateGame.hand?.find((item) => item.id === selected); const table = game.tableCards || []; const builds = Object.values(game.builds || {}); const moves = card ? legalCaptures(card, table, builds, me.team) : []; const buildCandidates = card && cardValue(card) !== null ? privateGame.hand.filter((item) => item.id !== card.id && cardValue(item) !== null).flatMap((required) => findCombinations(table, cardValue(required) - cardValue(card)).filter((set) => isValidBuild({ playedCard: card, selectedCards: set, hand: privateGame.hand }))) : []; const submit = async (move) => { try { await playMove({ roomCode: room.roomCode, playerId, ...move }); setSelected(null); setTargets([]); setMode('choose') } catch (error) { setMessage(error.message) } }; const toggle = (id) => setTargets((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); const current = Object.values(game.players).find((player) => player.slot === game.currentSlot); const captureSelection = moves.find((move) => !move.buildId && move.cardIds.length === targets.length && move.cardIds.every((id) => targets.includes(id))); const buildSelection = buildCandidates.find((set) => set.length === targets.length && set.every((item) => targets.includes(item.id))); const teamNames = (team) => Object.values(room.players || {}).filter((player) => player.team === team).sort((a, b) => a.slot - b.slot).map((player) => player.name).join(' + ')
  return <Shell><div className="mx-auto max-w-5xl py-4"><header className="flex items-center justify-between"><div><p className="text-xs text-amber-300">ROOM {room.roomCode} · ROUND {game.roundNumber}</p><h1 className="text-3xl font-black">CASSINO</h1></div><button className="text-sm underline" onClick={leave}>Leave</button></header><div className="mt-3 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><Score team="TEAM 1" names={teamNames(1)} score={game.scores?.[1] || 0} winning={(game.scores?.[1] || 0) > (game.scores?.[2] || 0)} /><b className="text-xs text-amber-300">VS</b><Score team="TEAM 2" names={teamNames(2)} score={game.scores?.[2] || 0} winning={(game.scores?.[2] || 0) > (game.scores?.[1] || 0)} /></div><div className="mt-3 grid gap-3 lg:grid-cols-[150px_1fr_150px]"><Players players={Object.values(game.players)} me={playerId} /><section className="rounded-3xl border border-[#52735d] bg-[#173128] p-4 shadow-xl"><div className="flex justify-between text-sm"><span className="tracking-widest">TABLE</span><b className={myTurn ? 'text-amber-300' : 'text-white/60'}>{myTurn ? '● YOUR TURN' : `WAITING FOR ${current?.name || 'PLAYER'}...`}</b></div><div className="mt-4 flex min-h-36 flex-wrap items-center justify-center gap-3">{table.map((item) => <Card key={item.id} card={item} small selected={targets.includes(item.id)} onClick={() => selected && myTurn && mode !== 'choose' && toggle(item.id)} />)}{builds.map((build) => <div key={build.id} className={`rounded-2xl border-2 border-amber-300/70 bg-[#254937] p-2 ${targets.includes(build.id) ? 'ring-2 ring-white' : ''}`}><p className="text-center text-xs font-black text-amber-200">BUILD {build.buildValue ?? build.value}</p><div className="flex gap-1">{build.cards.map((item) => <Card key={item.id} card={item} small />)}</div><button className="mt-1 w-full text-xs underline" onClick={() => selected && submit({ type: 'capture', cardId: selected, buildId: build.id })}>Capture</button></div>)}</div>{selected && myTurn && <ActionBar card={card} mode={mode} setMode={setMode} moves={moves} targets={targets} captureSelection={captureSelection} buildCandidates={buildCandidates} buildSelection={buildSelection} submit={submit} selected={selected} />}</section><Players players={Object.values(game.players).reverse()} me={playerId} /></div><section className="mt-3 rounded-3xl bg-[#14241e] p-4"><div className="flex items-center justify-between"><p className="text-xs tracking-widest">YOUR HAND · TEAM {me.team}</p><span className="text-xs text-white/60">Captured: {me.capturedCount || 0}</span></div><div className="mt-3 flex flex-wrap justify-center gap-2">{privateGame.hand?.map((item) => <Card key={item.id} card={item} selected={selected === item.id} onClick={() => { if (myTurn) { setSelected(item.id); setTargets([]); setMode('choose') } }} />)}</div></section></div></Shell> }

function ActionBar({ card, mode, setMode, moves, targets, captureSelection, buildCandidates, buildSelection, submit, selected }) { const equation = targets.length ? `${card.rank}${suitSymbol[card.suit]} + ${targets.map((id) => id.split('-')[0]).join(' + ')} = ${cardValue(card) + targets.reduce((sum, id) => sum + Number(id.split('-')[0] === 'A' ? 1 : id.split('-')[0]), 0)}` : 'Choose table cards'; return <div className="mt-4 rounded-2xl border border-amber-300/30 bg-black/20 p-3"><p className="text-sm font-bold">Selected card: <span className="text-amber-300">{card.rank}{suitSymbol[card.suit]}</span></p>{mode === 'choose' && <div className="mt-3 grid grid-cols-3 gap-2">{moves.length > 0 && <Button small onClick={() => setMode('capture')}>Capture</Button>}{buildCandidates.length > 0 && <Button small onClick={() => setMode('build')}>Build</Button>}<Button small secondary onClick={() => submit({ type: 'trail', cardId: selected })}>Trail card</Button></div>}{mode !== 'choose' && <><p className="mt-2 text-xs text-white/70">{mode === 'build' ? `BUILD VALUE · ${equation}` : 'Select table cards for a legal capture.'}</p><div className="mt-2 flex flex-wrap gap-2 text-sm">Selected: {targets.length ? targets.map((id) => <span key={id} className="text-amber-300">{id.split('-')[0]}</span>).join(' + ') : 'none'}</div>{mode === 'capture' && captureSelection && <Button small onClick={() => submit({ type: 'capture', cardId: selected, targetIds: targets })}>Confirm capture</Button>}{mode === 'build' && buildSelection && <Button small onClick={() => submit({ type: 'build', cardId: selected, targetIds: targets })}>Create build</Button>}<button className="ml-2 text-sm underline" onClick={() => setMode('choose')}>Cancel</button></>}</div> }

function Players({ players, me }) { return <aside className="grid grid-cols-3 gap-2 text-center text-xs lg:block">{players.map((player) => <div key={player.playerId} className={`rounded-xl bg-[#173128] p-2 lg:mb-2 ${player.playerId === me ? 'border border-amber-300' : ''}`}><b>{player.playerId === me ? 'YOU' : player.name}</b><p className="text-white/60">{player.handCount} cards</p><p className="text-white/60">Captured {player.capturedCount || 0}</p></div>)}</aside> }

function Result({ room, game, playerId, setMessage, leave }) { const result = game.roundResult; const teamNames = (team) => Object.values(room.players || {}).filter((player) => player.team === team).sort((a, b) => a.slot - b.slot).map((player) => player.name).join(' + '); const winner = result?.winner; const nextRound = () => startNextRound({ roomCode: room.roomCode, playerId }).catch((error) => setMessage(error.message)); const isHost = room.hostPlayerId === playerId; return <Shell><div className="mx-auto max-w-2xl py-8"><p className="text-center text-xs tracking-[.35em] text-amber-300">{winner ? 'FINAL TABLE' : `ROUND ${game.roundNumber} COMPLETE`}</p><h1 className="mt-2 text-center text-4xl font-black">{winner ? 'GAME OVER' : 'ROUND RESULT'}</h1><p className="mt-2 text-center text-xl font-bold text-amber-300">{winner ? `TEAM ${winner} WINS` : 'Scores added to the match'}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{[1, 2].map((team) => { const score = result?.scores?.[team] || {}; return <section key={team} className={`rounded-2xl border p-4 ${winner === team ? 'border-amber-300 bg-amber-300/10' : 'border-white/10 bg-white/5'}`}><p className="text-xs tracking-widest">TEAM {team}</p><h2 className="text-xl font-black">{teamNames(team)}</h2><p className="mt-3 text-4xl font-black">{result?.totalScores?.[team] || 0}<span className="ml-2 text-sm font-normal">points</span></p><div className="mt-4 space-y-1 text-sm text-white/70">{[['Big Casino', score.bigCasino], ['Little Casino', score.littleCasino], ['Aces', score.aces], ['Most Cards', score.mostCards], ['Most Spades', score.mostSpades], ['Sweeps', score.sweeps]].map(([label, value]) => <div className="flex justify-between" key={label}><span>{label}</span><b>{value}</b></div>)}</div><p className="mt-3 border-t border-white/10 pt-3 font-bold">Round points: {score.total || 0}</p></section> })}</div>{winner ? <Button onClick={leave}>Back to room</Button> : isHost ? <Button onClick={nextRound}>Next round</Button> : <p className="text-center text-sm text-white/60">Waiting for the host to start the next round...</p>}{!winner && <button className="mt-3 w-full text-sm underline" onClick={leave}>Back to room</button>}</div></Shell> }
function Shell({ children }) { return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#284b3d,#101b17_58%)] px-4 text-[#fff7e7]">{children}</main> }
function Score({ team, names, score, winning }) { return <div className={`rounded-xl p-2 ${winning ? 'bg-amber-300/20 ring-1 ring-amber-300' : 'bg-white/10'}`}><small>{team}</small><p className="truncate text-xs text-white/70">{names}</p><p className="text-2xl font-black">{score}<span className="ml-1 text-xs font-normal">points</span></p></div> }
function Field({ label, value, setValue, placeholder }) { return <label className="mt-4 block text-sm">{label}<input value={value} onChange={(event) => setValue(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl bg-[#10251c] p-3" /></label> }
function Button({ children, secondary, disabled, onClick, small }) { return <button disabled={disabled} onClick={onClick} className={`${small ? 'w-auto px-3 py-2 text-sm' : 'w-full px-4 py-3'} rounded-xl font-bold disabled:opacity-40 ${secondary ? 'border border-white/20' : 'bg-amber-400 text-[#172217]'}`}>{children}</button> }
function Message({ text }) { return text ? <p className="mt-4 text-center text-amber-200">{text}</p> : null }
