import { useEffect, useMemo, useState } from 'react'
import Card from '../components/Card'
import { firebaseEnabled } from '../firebase/config'
import { ensureAnonymousUser } from '../firebase/auth'
import { createRoom, joinRoom, playMove, setTeam, startRoom, watchPrivateGame, watchRoom } from '../firebase/database'
import { getPlayerId } from '../utils/roomCode'
import { legalCaptures } from '../game/captureRules'

const remembered = () => localStorage.getItem('casino_room_code') || ''
const invite = () => new URLSearchParams(location.search).get('room')?.trim().toUpperCase() || ''

export default function HomePage() {
  const playerId = useMemo(() => getPlayerId(), []); const savedRoom = useMemo(() => remembered(), []); const inviteRoom = useMemo(() => invite(), [])
  const [mode, setMode] = useState(savedRoom ? 'loading' : inviteRoom ? 'join' : 'home'); const [name, setName] = useState(''); const [roomCode, setRoomCode] = useState(savedRoom || inviteRoom); const [joinedRoom, setJoinedRoom] = useState(savedRoom)
  const [room, setRoom] = useState(null); const [privateGame, setPrivateGame] = useState(null); const [user, setUser] = useState(null); const [message, setMessage] = useState(firebaseEnabled ? 'Connecting…' : 'Firebase is not configured.')
  useEffect(() => { if (firebaseEnabled) ensureAnonymousUser().then((next) => { setUser(next); setMessage('') }).catch(() => setMessage('Could not connect to Firebase.')) }, [])
  useEffect(() => { if (!user || !joinedRoom) return; return watchRoom(joinedRoom, (next) => { setRoom(next); setMode(next ? (next.status === 'lobby' ? 'lobby' : 'game') : 'home'); if (!next) setMessage('Room not found.') }) }, [user, joinedRoom])
  useEffect(() => { if (!user || !joinedRoom || room?.status !== 'playing') return; return watchPrivateGame(joinedRoom, playerId, setPrivateGame) }, [user, joinedRoom, playerId, room?.status])
  const enter = async (task) => { if (!user) return setMessage('Still connecting.'); if (!name.trim()) return setMessage('Enter your name first.'); try { const code = await task(); localStorage.setItem('casino_room_code', code); setRoomCode(code); setJoinedRoom(code); setMessage('') } catch (error) { setMessage(error.message) } }
  const leave = () => { localStorage.removeItem('casino_room_code'); setJoinedRoom(''); setRoomCode(''); setRoom(null); setPrivateGame(null); setMode('home') }
  if (mode === 'lobby' && room) return <Lobby room={room} playerId={playerId} setMessage={setMessage} leave={leave} />
  if (mode === 'game' && room) return <Game room={room} privateGame={privateGame} playerId={playerId} setMessage={setMessage} leave={leave} />
  return <Shell><div className="mx-auto max-w-md pt-20 text-center"><p className="text-xs tracking-[.4em] text-amber-300">CLASSIC CARD GAME</p><h1 className="mt-2 text-6xl font-black">CASSINO</h1>{mode === 'home' ? <div className="mt-10 grid gap-3"><Button onClick={() => setMode('create')}>Create game</Button><Button secondary onClick={() => setMode('join')}>Join game</Button></div> : <div className="mt-10 rounded-3xl bg-[#173128] p-5 text-left"><h2 className="text-xl font-black">{mode === 'join' ? 'Join a game' : 'Create a game'}</h2>{mode === 'join' && <Field label="Room code" value={roomCode} setValue={(value) => setRoomCode(value.toUpperCase())} placeholder="AB7K9C" /> }<Field label="Your name" value={name} setValue={setName} placeholder="Saroj" /><Button onClick={() => mode === 'join' ? enter(() => joinRoom({ roomCode, playerId, authUid: user.uid, name })) : enter(() => createRoom({ playerId, authUid: user.uid, name }))}>{mode === 'join' ? 'Join room' : 'Create room'}</Button><button className="mt-4 w-full text-sm underline" onClick={() => setMode('home')}>Back</button></div>}<Message text={message} /></div></Shell>
}

function Lobby({ room, playerId, setMessage, leave }) { const players = Object.values(room.players || {}).sort((a, b) => a.slot - b.slot); const host = room.hostPlayerId === playerId; const counts = players.reduce((all, player) => ({ ...all, [player.team]: (all[player.team] || 0) + 1 }), {}); const ready = players.length === 4 && counts[1] === 2 && counts[2] === 2
  return <Shell><div className="mx-auto max-w-xl py-8"><h1 className="text-center text-4xl font-black">CASSINO</h1><section className="mt-5 rounded-3xl bg-[#173128] p-5 text-center"><p className="text-xs tracking-widest">ROOM CODE</p><p className="text-4xl font-black tracking-[.2em] text-amber-300">{room.roomCode}</p><button className="mt-3 text-sm underline" onClick={() => navigator.clipboard.writeText(room.roomCode)}>Copy code</button></section><section className="mt-4 rounded-3xl bg-[#173128] p-5"><div className="mb-3 flex justify-between"><b>Players</b><span>{players.length}/4</span></div>{[1,2,3,4].map((slot) => { const player = players.find((item) => item.slot === slot); return <div key={slot} className="mb-2 flex items-center justify-between rounded-xl bg-black/20 p-3">{player ? <><span><b>{player.name}</b> <small>Player {slot} {player.isHost && 'HOST'}</small></span>{host ? <select disabled={room.teamsLocked} value={player.team} onChange={(event) => setTeam({ roomCode: room.roomCode, playerId, hostPlayerId: room.hostPlayerId, targetPlayerId: player.playerId, team: Number(event.target.value) }).catch((error) => setMessage(error.message))} className="rounded bg-[#244638] p-1"><option value={1}>Team 1</option><option value={2}>Team 2</option></select> : <span>Team {player.team}</span>}</> : <span>Waiting for Player {slot}</span>}</div> })}</section>{host ? <div className="mt-4"><Button disabled={!ready} onClick={() => startRoom({ roomCode: room.roomCode, playerId }).catch((error) => setMessage(error.message))}>{ready ? 'Start game' : 'Need 4 players · 2 per team'}</Button></div> : <p className="mt-5 text-center">Waiting for host to start…</p>}<button className="mt-6 w-full text-sm underline" onClick={leave}>Leave</button></div></Shell> }

function Game({ room, privateGame, playerId, setMessage, leave }) { const [selected, setSelected] = useState(null); const [targets, setTargets] = useState([]); const game = room.game; const me = game?.players?.[playerId]; if (!game || !me || !privateGame) return <Shell><p className="pt-28 text-center">Dealing cards…</p></Shell>; const myTurn = game.currentSlot === me.slot; const card = privateGame.hand?.find((item) => item.id === selected); const moves = card ? legalCaptures(card, game.tableCards || [], Object.values(game.builds || {}), me.team) : []; const submit = async (move) => { try { await playMove({ roomCode: room.roomCode, playerId, ...move }); setSelected(null); setTargets([]) } catch (error) { setMessage(error.message) } }; const toggle = (id) => setTargets((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); const current = Object.values(game.players).find((player) => player.slot === game.currentSlot)
  return <Shell><div className="mx-auto max-w-4xl py-5"><header className="flex justify-between"><div><p className="text-xs text-amber-300">ROOM {room.roomCode}</p><h1 className="text-3xl font-black">CASSINO</h1></div><button className="text-sm underline" onClick={leave}>Leave</button></header><div className="mt-4 grid grid-cols-2 gap-3"><Score team="TEAM 1" score={game.scores?.[1] || 0} /><Score team="TEAM 2" score={game.scores?.[2] || 0} /></div><section className="mt-4 rounded-3xl bg-[#173128] p-5"><div className="flex justify-between text-sm"><span>ROUND {game.roundNumber}</span><b className={myTurn ? 'text-amber-300' : ''}>{myTurn ? 'YOUR TURN' : `WAITING FOR ${current?.name?.toUpperCase()}…`}</b></div><p className="mt-5 text-xs tracking-widest">TABLE {selected && '· select cards for a build'}</p><div className="mt-3 flex min-h-24 flex-wrap gap-3">{game.tableCards?.map((item) => <Card key={item.id} card={item} small selected={targets.includes(item.id)} onClick={() => selected && myTurn && toggle(item.id)} />)}</div></section><section className="mt-4 rounded-3xl bg-[#14241e] p-5"><p className="text-xs tracking-widest">YOUR HAND · TEAM {me.team}</p><div className="mt-4 flex flex-wrap justify-center gap-2">{privateGame.hand?.map((item) => <Card key={item.id} card={item} selected={selected === item.id} onClick={() => { if (myTurn) { setSelected(item.id); setTargets([]) } }} />)}</div>{selected && myTurn && <div className="mt-5 flex flex-wrap justify-center gap-2"><Button small secondary onClick={() => submit({ type: 'trail', cardId: selected })}>Trail</Button>{moves.map((move, index) => <Button small key={`${move.type}-${index}`} onClick={() => submit({ type: 'capture', cardId: selected, targetIds: move.cardIds, buildId: move.buildId })}>Capture {move.type === 'build' ? 'build' : `(${move.cardIds.length})`}</Button>)}{targets.length > 0 && <Button small onClick={() => submit({ type: 'build', cardId: selected, targetIds: targets })}>Create build</Button>}</div>}</section></div></Shell> }
function Shell({ children }) { return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#284b3d,#101b17_58%)] px-4 text-[#fff7e7]">{children}</main> }
function Score({ team, score }) { return <div className="rounded-xl bg-white/10 p-3"><small>{team}</small><p className="text-3xl font-black">{score} <span className="text-sm">/21</span></p></div> }
function Field({ label, value, setValue, placeholder }) { return <label className="mt-4 block text-sm">{label}<input value={value} onChange={(event) => setValue(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl bg-[#10251c] p-3" /></label> }
function Button({ children, secondary, disabled, onClick, small }) { return <button disabled={disabled} onClick={onClick} className={`${small ? 'w-auto px-3 py-2 text-sm' : 'w-full px-4 py-3'} rounded-xl font-bold disabled:opacity-40 ${secondary ? 'border border-white/20' : 'bg-amber-400 text-[#172217]'}`}>{children}</button> }
function Message({ text }) { return text ? <p className="mt-4 text-center text-amber-200">{text}</p> : null }
